USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS SENTINEL_ADMIN;
GRANT ROLE SENTINEL_ADMIN TO USER <your_user>;

CREATE WAREHOUSE IF NOT EXISTS SENTINEL_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

CREATE RESOURCE MONITOR SENTINEL_RM WITH CREDIT_QUOTA = 150
  TRIGGERS ON 75 PERCENT DO NOTIFY
           ON 90 PERCENT DO SUSPEND
           ON 100 PERCENT DO SUSPEND_IMMEDIATE;
ALTER WAREHOUSE SENTINEL_WH SET RESOURCE_MONITOR = SENTINEL_RM;

CREATE DATABASE IF NOT EXISTS SENTINEL_DB;
CREATE SCHEMA IF NOT EXISTS SENTINEL_DB.RAW;
CREATE SCHEMA IF NOT EXISTS SENTINEL_DB.CORE;
CREATE SCHEMA IF NOT EXISTS SENTINEL_DB.RISK;
CREATE SCHEMA IF NOT EXISTS SENTINEL_DB.DOCS;
CREATE SCHEMA IF NOT EXISTS SENTINEL_DB.APP;
CREATE SCHEMA IF NOT EXISTS SENTINEL_DB.AUDIT;
GRANT ALL ON DATABASE SENTINEL_DB TO ROLE SENTINEL_ADMIN;
GRANT USAGE, OPERATE ON WAREHOUSE SENTINEL_WH TO ROLE SENTINEL_ADMIN;


--  HFTPCWG-PH93773
--  JAYDHANWALKAR